name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: tradingeconomics
        path: tradingeconomics.html
        retention-days: 30
        - name: Get the latest artifact URL
        id: get-artifact-url
        run: echo "::set-output name=url::$(echo ${{ steps.upload-artifact.outputs.artifact-url }})"

      - name: Create Redirect Page
        run: |
          echo "<html><head><meta http-equiv=\"refresh\" content=\"0; url=${{ steps.get-artifact-url.outputs.url }}\"></head><body></body></html>" > index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
